// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0epHdt9PFOr9ozHJB4SqF2GZGMRCePQ4',
    appId: '1:660094311643:web:8ab5f9efa7c34d757680fe',
    messagingSenderId: '660094311643',
    projectId: 'app-convert-money',
    authDomain: 'app-convert-money.firebaseapp.com',
    storageBucket: 'app-convert-money.firebasestorage.app',
    measurementId: 'G-C8XFGZPQF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC3f_nOA7AkZ1FpzYeWKMtt-gW8kM2T9I',
    appId: '1:660094311643:android:9a062e807ed316a47680fe',
    messagingSenderId: '660094311643',
    projectId: 'app-convert-money',
    storageBucket: 'app-convert-money.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv3OTqDBkmXJeNnT0-m_k3aJZ3YRW0FCo',
    appId: '1:660094311643:ios:7a78e9911e0d49d77680fe',
    messagingSenderId: '660094311643',
    projectId: 'app-convert-money',
    storageBucket: 'app-convert-money.firebasestorage.app',
    iosBundleId: 'com.example.appConvertMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv3OTqDBkmXJeNnT0-m_k3aJZ3YRW0FCo',
    appId: '1:660094311643:ios:7a78e9911e0d49d77680fe',
    messagingSenderId: '660094311643',
    projectId: 'app-convert-money',
    storageBucket: 'app-convert-money.firebasestorage.app',
    iosBundleId: 'com.example.appConvertMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0epHdt9PFOr9ozHJB4SqF2GZGMRCePQ4',
    appId: '1:660094311643:web:f73a17661221cf667680fe',
    messagingSenderId: '660094311643',
    projectId: 'app-convert-money',
    authDomain: 'app-convert-money.firebaseapp.com',
    storageBucket: 'app-convert-money.firebasestorage.app',
    measurementId: 'G-1KWTSVJH55',
  );
}
